/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as CompleteUsernameRouteImport } from './routes/complete-username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsIndexRouteImport } from './routes/films/index'
import { Route as UserIdRouteImport } from './routes/user/$id'
import { Route as FilmsCategorieRouteImport } from './routes/films/$categorie'
import { Route as FilmIdRouteImport } from './routes/film/$id'

const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteUsernameRoute = CompleteUsernameRouteImport.update({
  id: '/complete-username',
  path: '/complete-username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsCategorieRoute = FilmsCategorieRouteImport.update({
  id: '/films/$categorie',
  path: '/films/$categorie',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-username': typeof CompleteUsernameRoute
  '/discussion': typeof DiscussionRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
  '/user/$id': typeof UserIdRoute
  '/films/': typeof FilmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-username': typeof CompleteUsernameRoute
  '/discussion': typeof DiscussionRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
  '/user/$id': typeof UserIdRoute
  '/films': typeof FilmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete-username': typeof CompleteUsernameRoute
  '/discussion': typeof DiscussionRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
  '/user/$id': typeof UserIdRoute
  '/films/': typeof FilmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-username'
    | '/discussion'
    | '/profil'
    | '/reglages'
    | '/film/$id'
    | '/films/$categorie'
    | '/user/$id'
    | '/films/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-username'
    | '/discussion'
    | '/profil'
    | '/reglages'
    | '/film/$id'
    | '/films/$categorie'
    | '/user/$id'
    | '/films'
  id:
    | '__root__'
    | '/'
    | '/complete-username'
    | '/discussion'
    | '/profil'
    | '/reglages'
    | '/film/$id'
    | '/films/$categorie'
    | '/user/$id'
    | '/films/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteUsernameRoute: typeof CompleteUsernameRoute
  DiscussionRoute: typeof DiscussionRoute
  ProfilRoute: typeof ProfilRoute
  ReglagesRoute: typeof ReglagesRoute
  FilmIdRoute: typeof FilmIdRoute
  FilmsCategorieRoute: typeof FilmsCategorieRoute
  UserIdRoute: typeof UserIdRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-username': {
      id: '/complete-username'
      path: '/complete-username'
      fullPath: '/complete-username'
      preLoaderRoute: typeof CompleteUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$categorie': {
      id: '/films/$categorie'
      path: '/films/$categorie'
      fullPath: '/films/$categorie'
      preLoaderRoute: typeof FilmsCategorieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteUsernameRoute: CompleteUsernameRoute,
  DiscussionRoute: DiscussionRoute,
  ProfilRoute: ProfilRoute,
  ReglagesRoute: ReglagesRoute,
  FilmIdRoute: FilmIdRoute,
  FilmsCategorieRoute: FilmsCategorieRoute,
  UserIdRoute: UserIdRoute,
  FilmsIndexRoute: FilmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
